name: easy_ecommerce
description: A new Flutter package project.
version: 0.0.2
author:
homepage:

environment:
  sdk: ">=2.10.4 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2
  equatable: ^2.0.0-nullsafety.1
  dio: ^3.0.0
  overlay_support: ^1.2.0-nullsafety.0
  shimmer: ^2.0.0-nullsafety.0
  flutter_bloc: ^7.0.0-nullsafety.1
  credit_card_number_validator: ^1.0.4
  flutter_staggered_grid_view: ^0.4.0-nullsafety.2
  carousel_slider: ^2.3.1
  flutter_svg: ^0.20.0-nullsafety.3
  shared_preferences: ^0.5.12+4
  dotted_border: ^2.0.0-nullsafety.0
  provider: ^5.0.0-nullsafety.3
  tinycolor: ^1.0.3
  awesome_dialog: ^1.3.1
  rxdart: ^0.25.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: Frutiger LT Arabic 55 Roman
      fonts:
        - asset: assets/fonts/FrutigerLTArabic-55Roman.ttf
  assets:
    - assets/
    - assets/images/
flutter_intl:
  enabled: true
  class_name: I18n
  main_locale: ar_SA
